apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventsource
  namespace: sit
  labels:
    app: eventsource
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventsource
  template:
    metadata:
      labels:
        app: eventsource
    spec:
      containers:
      - name: eventsource
        image: europe-west1-docker.pkg.dev/gke-super-duper-test/pkg-super-duper-test/eventsource:latest
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "10.212.0.3"
        - name: REDIS_PORT
          value: "6379"
        - name: BRANCH
          value: "sit"
---
apiVersion: v1
kind: Service
metadata:
  name: eventsource
  namespace: sit
spec:
  selector:
    app: eventsource
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
